/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tlpcraft.plugin.commitlint

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.tlpcraft.plugin.commitlint.greeting' plugin.
 */
class CommitlintPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.tlpcraft.plugin.commitlint.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
