/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tlpcraft.plugin.commitlint

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class CommitlintPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'com.tlpcraft.plugin.commitlint.greeting'")
            }
        }
    }
}
